"use client";
import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  CheckCircle2, 
  Circle, 
  Play, 
  Pause, 
  RotateCcw, 
  Clock, 
  Sparkles, 
  ShieldCheck, 
  Copy, 
  Check, 
  Download, 
  X, 
  Flame, 
  Zap, 
  Volume2, 
  VolumeX,
  Target
} from "lucide-react";
import { RescuePlan, RescueActionStep } from "@/types";
import { cyberAudio } from "@/lib/audio";

interface FocusMissionModalProps {
  rescuePlan: RescuePlan | null;
  isOpen: boolean;
  onClose: () => void;
  onMissionCompleted?: () => void;
}

export default function FocusMissionModal({
  rescuePlan,
  isOpen,
  onClose,
  onMissionCompleted,
}: FocusMissionModalProps) {
  const [completedStepIds, setCompletedStepIds] = useState<string[]>([]);
  const [activeStepIndex, setActiveStepIndex] = useState(0);
  const [timerSeconds, setTimerSeconds] = useState(25 * 60); // 25 min default pomodoro
  const [isTimerRunning, setIsTimerRunning] = useState(false);
  const [copied, setCopied] = useState(false);
  const [showCelebration, setShowCelebration] = useState(false);

  // Initialize timer with first step time
  useEffect(() => {
    if (rescuePlan && rescuePlan.rescueActions && rescuePlan.rescueActions.length > 0) {
      const firstMins = rescuePlan.rescueActions[0].estimatedMinutes || 25;
      setTimerSeconds(firstMins * 60);
      setCompletedStepIds([]);
      setActiveStepIndex(0);
      setIsTimerRunning(false);
      setShowCelebration(false);
    }
  }, [rescuePlan, isOpen]);

  // Stopwatch/Countdown Tick
  useEffect(() => {
    let interval: NodeJS.Timeout | null = null;
    if (isTimerRunning && timerSeconds > 0) {
      interval = setInterval(() => {
        setTimerSeconds((prev) => prev - 1);
      }, 1000);
    } else if (timerSeconds === 0 && isTimerRunning) {
      setIsTimerRunning(false);
      cyberAudio.playStepComplete();
    }
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [isTimerRunning, timerSeconds]);

  if (!isOpen || !rescuePlan) return null;

  const totalSteps = rescuePlan.rescueActions?.length || 0;
  const completedCount = completedStepIds.length;
  const progressPercent = totalSteps > 0 ? Math.round((completedCount / totalSteps) * 100) : 0;

  const handleToggleStep = (step: RescueActionStep, index: number) => {
    const isDone = completedStepIds.includes(step.id);
    let nextDone: string[];

    if (isDone) {
      nextDone = completedStepIds.filter((id) => id !== step.id);
      cyberAudio.playActionClick();
    } else {
      nextDone = [...completedStepIds, step.id];
      cyberAudio.playStepComplete();

      // Check if all completed
      if (nextDone.length === totalSteps) {
        setShowCelebration(true);
        cyberAudio.playSuccessFanfare();
        if (onMissionCompleted) onMissionCompleted();
      } else {
        // Set next active step
        const nextIdx = (index + 1) % totalSteps;
        setActiveStepIndex(nextIdx);
        if (rescuePlan.rescueActions[nextIdx]) {
          setTimerSeconds((rescuePlan.rescueActions[nextIdx].estimatedMinutes || 25) * 60);
        }
      }
    }
    setCompletedStepIds(nextDone);
  };

  const formatTimer = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  };

  const handleCopyReport = () => {
    cyberAudio.playActionClick();
    const markdown = `# RESCUEFLOW TACTICAL MISSION REPORT
**Productivity Score:** ${rescuePlan.productivityScore}%
**Chaos Assessment:** ${rescuePlan.chaosLevel}
**Tactical Mantra:** "${rescuePlan.tacticalMantra}"

## Executive Summary
${rescuePlan.analysisSummary}

## Triage Action Sequence
${rescuePlan.rescueActions.map((s, i) => `${i + 1}. [${completedStepIds.includes(s.id) ? "x" : " "}] **${s.title}** (${s.estimatedMinutes}m, Priority: ${s.priorityLevel})\n   *Rationale:* ${s.rationale}`).join("\n")}

## 15-Minute Quick Wins
${rescuePlan.quickWins?.map((w, i) => `- ${w}`).join("\n") || "None listed"}

---
*Generated by RescueFlow Command Center*
`;

    navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center bg-[#020617]/95 backdrop-blur-2xl p-4 sm:p-6 overflow-y-auto">
      <motion.div
        initial={{ scale: 0.85, opacity: 0, y: 30 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.85, opacity: 0, y: 30 }}
        className="w-full max-w-4xl bg-gradient-to-b from-slate-900/90 to-slate-950/95 border border-cyan-500/30 rounded-[2.5rem] p-6 sm:p-10 shadow-[0_0_100px_rgba(6,182,212,0.15)] relative text-slate-100 my-auto overflow-hidden"
      >
        {/* Futuristic Corner HUD Accents */}
        <div className="absolute top-6 left-6 w-10 h-10 border-t-2 border-l-2 border-cyan-500/50 rounded-tl-xl pointer-events-none" />
        <div className="absolute top-6 right-6 w-10 h-10 border-t-2 border-r-2 border-cyan-500/50 rounded-tr-xl pointer-events-none" />
        <div className="absolute bottom-6 left-6 w-10 h-10 border-b-2 border-l-2 border-cyan-500/50 rounded-bl-xl pointer-events-none" />
        <div className="absolute bottom-6 right-6 w-10 h-10 border-b-2 border-r-2 border-cyan-500/50 rounded-br-xl pointer-events-none" />

        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute top-6 right-6 z-20 p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition-colors"
        >
          <X size={20} />
        </button>

        {/* Header */}
        <div className="text-center mb-8">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-[10px] font-mono font-bold tracking-[0.25em] uppercase mb-2">
            <Sparkles size={12} /> Tactical Focus Mission
          </div>
          <h2 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
            RESCUE MISSION PROTOCOL
          </h2>
          <p className="text-cyan-400/80 text-xs sm:text-sm font-medium italic mt-1 max-w-xl mx-auto">
            &ldquo;{rescuePlan.tacticalMantra}&rdquo;
          </p>
        </div>

        {/* Mission Progress Bar */}
        <div className="mb-8 p-4 rounded-2xl bg-white/[0.03] border border-white/10">
          <div className="flex justify-between items-center text-xs font-mono mb-2">
            <span className="text-slate-400 uppercase font-bold flex items-center gap-1.5">
              <ShieldCheck size={14} className="text-cyan-400" /> Mission Progress
            </span>
            <span className="text-cyan-400 font-bold">
              {completedCount} / {totalSteps} Steps ({progressPercent}%)
            </span>
          </div>
          <div className="h-2.5 bg-white/10 rounded-full overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${progressPercent}%` }}
              transition={{ duration: 0.4 }}
              className="h-full bg-gradient-to-r from-cyan-500 to-emerald-400 shadow-[0_0_12px_#06b6d4]"
            />
          </div>
        </div>

        {/* 2-Column Content: Left = Triage Steps, Right = Tactical Timer & Quick Wins */}
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-6 mb-8">
          {/* Triage Checklist (3 cols) */}
          <div className="lg:col-span-3 space-y-3">
            <h3 className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
              <Flame size={14} className="text-cyan-400" /> Sequential Action Queue
            </h3>

            <div className="space-y-3 max-h-[380px] overflow-y-auto pr-1">
              {rescuePlan.rescueActions.map((step, idx) => {
                const isDone = completedStepIds.includes(step.id);
                const isActive = activeStepIndex === idx;

                return (
                  <motion.div
                    key={step.id || idx}
                    initial={{ opacity: 0, x: -15 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: idx * 0.08 }}
                    onClick={() => handleToggleStep(step, idx)}
                    className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-start gap-3.5 group relative ${
                      isDone
                        ? "bg-emerald-950/15 border-emerald-500/30 opacity-70"
                        : isActive
                        ? "bg-cyan-950/30 border-cyan-500/60 shadow-[0_0_20px_rgba(6,182,212,0.2)]"
                        : "bg-white/[0.03] border-white/10 hover:border-white/20 hover:bg-white/[0.06]"
                    }`}
                  >
                    <button
                      type="button"
                      className="mt-0.5 text-slate-500 group-hover:text-cyan-400 transition-colors flex-shrink-0"
                    >
                      {isDone ? (
                        <CheckCircle2 size={20} className="text-emerald-400" />
                      ) : (
                        <Circle size={20} />
                      )}
                    </button>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between gap-2 mb-1">
                        <span className="text-[10px] font-mono text-cyan-400 font-bold uppercase tracking-wider">
                          Step 0{idx + 1} • {step.priorityLevel}
                        </span>
                        <span className="text-[11px] font-mono text-slate-400 flex items-center gap-1">
                          <Clock size={11} /> {step.estimatedMinutes}m
                        </span>
                      </div>

                      <h4
                        className={`text-sm font-bold leading-snug ${
                          isDone ? "line-through text-slate-400" : "text-white"
                        }`}
                      >
                        {step.title}
                      </h4>
                      <p className="text-xs text-slate-400 mt-1 leading-relaxed">
                        {step.rationale}
                      </p>
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>

          {/* Right Column: Focus Timer & Quick Wins (2 cols) */}
          <div className="lg:col-span-2 space-y-4">
            {/* Tactical Focus Timer */}
            <div className="p-6 rounded-3xl bg-white/[0.03] border border-white/10 backdrop-blur-xl text-center relative overflow-hidden">
              <div className="text-[10px] font-mono font-bold tracking-widest text-slate-400 uppercase mb-2">
                Active Tactical Timer
              </div>

              {/* Timer Display */}
              <div className="text-5xl font-black font-mono text-white tracking-tight my-3 drop-shadow-[0_0_20px_rgba(6,182,212,0.4)]">
                {formatTimer(timerSeconds)}
              </div>

              {/* Timer Controls */}
              <div className="flex items-center justify-center gap-2 mt-4">
                <button
                  type="button"
                  onClick={() => {
                    cyberAudio.playActionClick();
                    setIsTimerRunning(!isTimerRunning);
                  }}
                  className={`px-5 py-2.5 rounded-xl font-bold text-xs flex items-center gap-1.5 transition-all ${
                    isTimerRunning
                      ? "bg-amber-500 text-slate-950 hover:bg-amber-400"
                      : "bg-cyan-500 text-slate-950 hover:bg-cyan-400 shadow-[0_0_15px_rgba(6,182,212,0.4)]"
                  }`}
                >
                  {isTimerRunning ? <Pause size={14} /> : <Play size={14} />}
                  <span>{isTimerRunning ? "Pause" : "Start Focus"}</span>
                </button>

                <button
                  type="button"
                  onClick={() => {
                    cyberAudio.playActionClick();
                    setIsTimerRunning(false);
                    setTimerSeconds(25 * 60);
                  }}
                  title="Reset to 25m"
                  className="p-2.5 rounded-xl bg-white/5 hover:bg-white/10 text-slate-400 hover:text-white transition-colors border border-white/5"
                >
                  <RotateCcw size={14} />
                </button>
              </div>

              {/* Quick Time Adders */}
              <div className="flex justify-center gap-1.5 mt-3">
                {[5, 15, 25].map((m) => (
                  <button
                    key={m}
                    type="button"
                    onClick={() => {
                      cyberAudio.playActionClick();
                      setTimerSeconds((prev) => prev + m * 60);
                    }}
                    className="text-[10px] font-mono px-2 py-0.5 rounded bg-white/5 hover:bg-cyan-500/20 text-slate-400 hover:text-cyan-300 border border-white/5 transition-colors"
                  >
                    +{m}m
                  </button>
                ))}
              </div>
            </div>

            {/* Tactical Quick Wins */}
            {rescuePlan.quickWins && (
              <div className="p-4 rounded-2xl bg-white/[0.02] border border-white/5 space-y-2">
                <div className="text-[10px] font-mono font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Zap size={12} /> Instant Relief
                </div>
                {rescuePlan.quickWins.slice(0, 2).map((win, i) => (
                  <p key={i} className="text-[11px] text-slate-300 leading-snug">
                    • {win}
                  </p>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pt-6 border-t border-white/10">
          <button
            type="button"
            onClick={handleCopyReport}
            className="w-full sm:w-auto px-5 py-3 rounded-2xl bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white text-xs font-mono font-bold flex items-center justify-center gap-2 transition-colors"
          >
            {copied ? <Check size={14} className="text-emerald-400" /> : <Copy size={14} />}
            <span>{copied ? "Report Copied to Clipboard!" : "Export Tactical Briefing"}</span>
          </button>

          <button
            type="button"
            onClick={onClose}
            className="w-full sm:w-auto px-8 py-3.5 rounded-2xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-black text-sm uppercase tracking-widest shadow-[0_0_25px_rgba(6,182,212,0.4)] transition-all hover:scale-105 active:scale-95"
          >
            {completedCount === totalSteps ? "Mission Debrief Completed" : "Return to Radar"}
          </button>
        </div>

        {/* Celebration Overlay */}
        <AnimatePresence>
          {showCelebration && (
            <motion.div
              initial={{ opacity: 0, scale: 0.8 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0 }}
              className="absolute inset-0 bg-slate-950/95 backdrop-blur-2xl z-30 flex flex-col items-center justify-center p-8 text-center"
            >
              <motion.div
                initial={{ rotate: -15, scale: 0 }}
                animate={{ rotate: 0, scale: 1 }}
                className="p-5 rounded-full bg-emerald-500/20 border border-emerald-500/50 text-emerald-400 mb-6 shadow-[0_0_50px_rgba(16,185,129,0.4)]"
              >
                <ShieldCheck size={64} />
              </motion.div>

              <h3 className="text-4xl font-black text-white tracking-tight mb-2">
                CHAOS NEUTRALIZED!
              </h3>
              <p className="text-slate-300 text-sm max-w-md mx-auto mb-8">
                All triage vectors successfully resolved. Tactical execution score restored to peak efficiency.
              </p>

              <div className="flex gap-4">
                <button
                  type="button"
                  onClick={() => setShowCelebration(false)}
                  className="px-6 py-3 rounded-2xl bg-emerald-500 hover:bg-emerald-400 text-slate-950 font-bold text-sm uppercase tracking-wider shadow-[0_0_20px_rgba(16,185,129,0.4)] transition-all hover:scale-105"
                >
                  View Completed Mission
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  );
}
