import { Task } from "@/types";

export interface PresetScenario {
  id: string;
  name: string;
  badge: string;
  description: string;
  tasks: Omit<Task, "id" | "createdAt">[];
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: "startup-pitch",
    name: "Startup Pitch Fire Drill",
    badge: "CRITICAL ALERT",
    description: "3 hours before Series-A demo meeting, production app is crashing and slides are unfinished.",
    tasks: [
      {
        title: "Fix UI Deployment Crash on Vercel",
        description: "SSR hydration mismatch breaking the dashboard during live investor demo walkthrough.",
        deadline: "In 45 mins",
        priority: "Critical",
        risk: 95,
        estimatedMinutes: 30,
        category: "Technical",
        status: "pending",
      },
      {
        title: "Finalize Pitch Deck Financial Moat Slide",
        description: "Update MRR projections and unit economics to match the latest churn metrics.",
        deadline: "In 90 mins",
        priority: "High",
        risk: 85,
        estimatedMinutes: 40,
        category: "Strategy",
        status: "pending",
      },
      {
        title: "Rehearse Demo Script & Objection Handling",
        description: "Do a 10-minute speed run of the user onboarding flow.",
        deadline: "In 2 hours",
        priority: "Medium",
        risk: 60,
        estimatedMinutes: 20,
        category: "Communication",
        status: "pending",
      },
      {
        title: "Verify Stripe Webhook sandbox keys",
        description: "Ensure test card numbers function during live checkout payment demonstration.",
        deadline: "In 2.5 hours",
        priority: "High",
        risk: 75,
        estimatedMinutes: 15,
        category: "Technical",
        status: "pending",
      },
      {
        title: "Send Calendar Confirmation with Zoom Link",
        description: "Send calendar update to Lead Partner and Associates.",
        deadline: "Today 4pm",
        priority: "Low",
        risk: 25,
        estimatedMinutes: 10,
        category: "Operations",
        status: "pending",
      },
    ],
  },
  {
    id: "production-outage",
    name: "Sev-1 Production Outage",
    badge: "INCIDENT RESPONSE",
    description: "Database connection pool saturated, 504 errors on core API endpoints.",
    tasks: [
      {
        title: "Isolate Broken Migration & Revert Database",
        description: "Unindexed foreign key migration locking user table in Postgres.",
        deadline: "IMMEDIATE (15m)",
        priority: "Critical",
        risk: 98,
        estimatedMinutes: 20,
        category: "Technical",
        status: "pending",
      },
      {
        title: "Broadcast Status Page Incident Update",
        description: "Post public incident acknowledgment to reduce support ticket avalanche.",
        deadline: "In 10m",
        priority: "High",
        risk: 80,
        estimatedMinutes: 5,
        category: "Communication",
        status: "pending",
      },
      {
        title: "Scale Read Replicas on AWS RDS",
        description: "Spin up 2 extra compute nodes to absorb traffic backlog.",
        deadline: "In 30m",
        priority: "High",
        risk: 70,
        estimatedMinutes: 15,
        category: "Operations",
        status: "pending",
      },
      {
        title: "Draft Post-Mortem Timeline",
        description: "Record commit SHA, alarm timestamps, and blast radius for engineering retro.",
        deadline: "Tomorrow",
        priority: "Low",
        risk: 30,
        estimatedMinutes: 45,
        category: "Strategy",
        status: "pending",
      },
    ],
  },
  {
    id: "academic-crunch",
    name: "Finals & Thesis Crunch",
    badge: "DEADLINE AVALANCHE",
    description: "Thesis submission and final defense presentation due simultaneously.",
    tasks: [
      {
        title: "Submit Neural Network Paper PDF to Portal",
        description: "Finalize bibliography citations and check IEEE formatting margins.",
        deadline: "Today, 11:59 PM",
        priority: "Critical",
        risk: 90,
        estimatedMinutes: 60,
        category: "Technical",
        status: "pending",
      },
      {
        title: "Generate Benchmark Loss Curves Chart",
        description: "Export high-res vector charts from Weights & Biases for paper figure 4.",
        deadline: "In 3 hours",
        priority: "High",
        risk: 70,
        estimatedMinutes: 25,
        category: "Design",
        status: "pending",
      },
      {
        title: "Email Committee Advisor for Defense Approval",
        description: "Attach draft 3 with change changelog.",
        deadline: "Tomorrow 9 AM",
        priority: "Medium",
        risk: 45,
        estimatedMinutes: 15,
        category: "Communication",
        status: "pending",
      },
      {
        title: "Review Algorithm Proofs Chapter 3",
        description: "Verify mathematical induction step for Lemma 2.",
        deadline: "Tomorrow 2 PM",
        priority: "Medium",
        risk: 50,
        estimatedMinutes: 45,
        category: "Strategy",
        status: "pending",
      },
    ],
  },
  {
    id: "freelancer-overload",
    name: "Solo Agency Overload",
    badge: "OVERWHELMED",
    description: "Multiple client deliverables conflicting with pending contract signings.",
    tasks: [
      {
        title: "Deliver Brand Guidelines PDF to Client A",
        description: "Package figma assets, typography licenses, and logo variations.",
        deadline: "Today, 5 PM",
        priority: "High",
        risk: 85,
        estimatedMinutes: 50,
        category: "Design",
        status: "pending",
      },
      {
        title: "Send Overdue Retainer Invoice ($4,500)",
        description: "Follow up with accounting department before end of month billing cycle.",
        deadline: "Today",
        priority: "High",
        risk: 75,
        estimatedMinutes: 10,
        category: "Operations",
        status: "pending",
      },
      {
        title: "Fix Shopify Checkout Styling Glitch",
        description: "Mobile viewport button overlap on iOS Safari.",
        deadline: "Tomorrow morning",
        priority: "Medium",
        risk: 60,
        estimatedMinutes: 30,
        category: "Technical",
        status: "pending",
      },
      {
        title: "Reply to 14 Backlogged Slack Inquiries",
        description: "Batch responses to clarify sprint scope.",
        deadline: "End of day",
        priority: "Low",
        risk: 35,
        estimatedMinutes: 25,
        category: "Communication",
        status: "pending",
      },
    ],
  },
];
